[{"matnr":"EFL06115",
"manuscrito":"0181609",
"manuscrito_grupo":"MES-112956",
"isbn":"9788417906115",
"cod_autor":"0000937676",
"titulo":"Los posthumanos",
"subtitulo":"",
"region":"ES",
"digital":"X",
"autor":"Siddhartha Mukherjee",
"cod_sello_editorial":"FH",
"sello_editorial":"FLASH",
"pvp":"1.49",
"coleccion":"Flash",
"genero_1":"",
"fecha_nov":"20190909",
"sinopsis":"<p style=\"text-align:center\"><B>\u00bfQu\u00e9 pasar\u00e1 cuando dominemos completamente nuestro genoma?<\/B><\/P> <p style=\"text-align:center\"><\/P> <p style=\"text-align:center\"><B>\u00bfPodremos crear, en nombre de la ciencia, posthumanos capaces de  superar las enfermedades que nos asolan en la actualidad?<\/B><\/P>","contratapa":"<P>Siddhartha Mukherjee, ganador del Premio Pulitzer por <I>El emperador de todos los males<\/I>, nos ofrece una detallada visi\u00f3n de lo que puede a  llegar a convertirse la raza humana si es que, en el futuro, todav\u00eda podemos llamarla as\u00ed.<\/P>  <P><B>Sobre <\/B><I><B>El gen<\/B><\/I><B>:<\/B><BR>\u00abEsta quiz\u00e1 sea la mejor historia de suspense jam\u00e1s contada, una  b\u00fasqueda de milenios dirigida por mil exploradores, de Arist\u00f3teles a  Mendel a Francis Collins, tras el enigma en el centro de cada c\u00e9lula. Como <I>El emperador de todos los males<\/I>, <I>El gen<\/I> es prodigiosa,  torrencial y finalmente transcendente. Si te interesa en qu\u00e9 consiste  ser humano hoy y en todos los ma\u00f1anas que vengan, tienes que  leer este libro.\u00bb<BR>Anthony Doerr, autor de <I>La luz que no puedes ver<\/I><\/P> <P>\u00ab<I>El gen<\/I> es una magn\u00edfica s\u00edntesis de la ciencia de la vida, y nos  obliga a enfrentarnos con el n\u00facleo de esa ciencia, as\u00ed como con los  retos \u00e9ticos y filos\u00f3ficos a nuestra idea de en qu\u00e9 consiste ser humano.\u00bb<BR>Paul Berg, Premio Nobel de Qu\u00edmica<\/P> <P>\u00abMagn\u00edfico... La historia del gen se ha contado por trozos de distintas  maneras, pero nunca con la perspectiva y la grandeza que Mukherjee aporta a su historia.\u00bb<BR>James Gleick, New York Times Book Review<\/P>",
"paginas":"20",
"medidas":"",
"idioma":"ES",
"cod_sector":"300",
"sector":"Adultos",
"portada":"http:\/\/static.megustaleer.com\/images\/libros_244_x\/EFL06115.jpg",
"imagen_autor":"http:\/\/static.megustaleer.com\/images\/autores_300_x\/0000937676.jpg",
"biografia":"<P><B>Siddhartha Mukherjee<\/B> es profesor de medicina en la Universidad de  Columbia, y onc\u00f3logo en su hospital universitario. Ganador de una beca  Rhodes, se gradu\u00f3 en la Universidad de Stanford y en la de Oxford, para  licenciarse en Medicina en la Universidad de Harvard. Ha publicado art\u00edculos en <I>Nature<\/I>, <I>The New England Journal of Medicine<\/I>, <I>The New York Times<\/I> y <I>The New Republic<\/I> y su libro <I>El  emperador de todos los males<\/I> (Debate, 2014) fue ganador del Premio  Pulitzer en la categor\u00eda de no ficci\u00f3n en el 2011. Actualmente, vive en Nueva York con su esposa y sus hijas.<\/P>",
"url_autor":"http:\/\/www.megustaleer.com\/autor\/siddhartha-mukherjee\/0000937676",
"url_libro":"http:\/\/www.megustaleer.com\/libros\/los-posthumanos\/MES-112956",
"ilustrador":"",
"traductor":"",
"keywords":"Flash, flash relatos, relato, relato corto, la mejor literatura breve, barato, port\u00e1til, corto, r\u00e1pido, ebook Flash, flash relatos,  relato, relato corto, ebook lovers, , megustaleer, me gusta leer, me gusta leer Ebooks, megustaleer Ebooks, malditas edito",
"url_booktrailer":"",
"narrador":"",
"duracion":"",
"url_audiolibro":"",
"formato":"E-book"}]
