[{
    "matnr":"AG00761",
    "isbn":"9788403500761",
    "cod_autor":"0000100746",
    "titulo":"Chocolate",
    "region":"ES",
    "digital":"",
    "autor":"Sandra Mangas",
    "cod_sello_editorial":"PA",
    "sello_editorial":"AGUILAR OCIO",
    "pvp":"21.9",
    "coleccion":"Gastronom\u00eda",
    "genero_1":"Ocio",
    "fecha_nov":"20151015",
    "sinopsis":"<p style=\"text-align:center\"><B>El chocolate es el gran capricho al que nadie puede resistirse porque  despierta nuestros sentidos y alimenta nuestras emociones -el aroma de  una taza de chocolate, la textura de una delicada mousse o el crujir de un perfecto macaron-.<\/B><\/P>","contratapa":"<p style=\"text-align:center\"><B>Ahora, gracias a este delicioso recetario de Sandra Mangas, podr\u00e1s  disfrutar de los dulces de chocolate m\u00e1s seductores al paladar en tu propia casa.<\/B><\/P> <P>Todos los lectores de <I>La Receta de la Felicidad<\/I>, el blog de cocina  de Sandra Mangas, saben que el ingrediente favorito de su autora es el  chocolate, con el que puede hacer aut\u00e9nticas maravillas reposteras. En  este libro encontrar\u00e1s 63 apetitosas recetas de postres y caprichos  dulces en las que el chocolate es el protagonista absoluto, y que  cumplen los principios fundamentales de Sandra: tener una elaboraci\u00f3n  sencilla y asequible al repostero aficionado, y una presentaci\u00f3n original y fuera de lo com\u00fan.<\/P> <P>Adem\u00e1s de las recetas que se han hecho cl\u00e1sicas en el blog de Sandra -el  falso huevo poch\u00e9, el turr\u00f3n Dulcey\u00ae, las berlinas rellenas o la tarta  sencilla sin huevo ni l\u00e1cteos- hay otras tantas in\u00e9ditas que sin duda  sorprender\u00e1n al lector por su creatividad y facilidad, como los bombones  Lego\u00ae, el chocoflan o la tarta Maltesers\u00ae-. Tambi\u00e9n hay un completo  apartado en el que se explican las bases  para dominar las t\u00e9cnicas  esenciales del chocolate, sin pretender ser un maestro repostero  -fundir, atemperar, moldear, ba\u00f1ar...- as\u00ed como las herramientas, los  tipos de chocolate y los otros ingredientes que combinan y armonizan con \u00e9l -mantequilla, az\u00facar, frutos secos o cremas-.<\/P> <p style=\"text-align:center\"><B>\u00a1Pi\u00e9rdele el miedo al ingrediente estrella de la reposter\u00eda!<\/B><BR>Este es el perfecto libro para iniciarte en la elaboraci\u00f3n de choco-<BR>lates sin complicaciones y con unos resultados de estrella Michel\u00edn.<\/P>",
    "subtitulo":"Recetas con un toque de felicidad",
    "url_booktrailer":null,
    "narrador":"",
    "ilustrador":"",
    "traductor":"",
    "keywords":"",
    "paginas":"192",
    "medidas":"200 X 266",
    "idioma":"ES",
    "zzbisac":"CKB018000",
    "portada":"http:\/\/static.megustaleer.com\/images\/libros_244_x\/AG00761.jpg"
    }]